version: '3.8'
services:
  gateway:
    build: gateway/.
    image: shareit_gate
    container_name: shareit_gate
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server/.
    image: shareit_serv
    container_name: shareit_serv
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit

  db:
    image: postgres:14-alpine
    container_name: shareit_database
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root